sudo: false

language: java
jdk:
  - openjdk8

script:
  - mvn clean package

services:
  - docker

after_success:
  - docker build -f Dockerfile -t server_app .
  - docker build -f Dockerfile -t client_app .

branches:
  only:
    - master